#!/bin/bash

# udpate & install the python libs
read -p "would you like to update your OS? (recommended) [y/n]" answer
if [[ $answer = y ]] ; then
    echo '=================================================='
    echo 'updating and upgrading...'
    sudo apt-get update
fi

read -p "would you like to install the python libs? (recommended) [y/n]"
if [[ $answer = y ]] ; then
echo '=================================================='
echo 'installing python libs and pip...'
sudo apt-get install python-dev python-setuptools
sudo apt-get install python-pip
sudo apt-get install libjpeg-dev
sudo apt-get install python-imaging-tk
sudo pip install pibrella
sudo pip install Pillow # this is for PIL
fi

# install
if [ ! -f ~/Desktop/netapp ]; then
   echo '=================================================='
   echo 'installing...'
   cp ~/net-hub-pi/app/netapp ~/Desktop
   chmod +x ~/Desktop/netapp
else
   echo '=================================================='
   echo 'updating...'
   rm ~/Desktop/netapp
   cp ~/net-hub-pi/app/netapp ~/Desktop
   chmod +x ~/Desktop/netapp
fi

# set double click?
if [ ! -f ~/.gtkrc-2.0 ]; then
   cp ~/net-hub-pi/app/.gtkrc-2.0 ~
   #. ~/.gtkrc-2.0
else
   echo '>> You may need to change the double click speed in your .gtkrc file'
fi

echo '=================================================='
echo 'done!'